-- ================================================
-- MySite — Supabase Schema
-- Jalankan ini di: Supabase → SQL Editor → Run
-- ================================================

-- NOTES / JOURNAL
create table if not exists notes (
  id          uuid primary key default gen_random_uuid(),
  title       text,
  content     text not null,
  image_url   text,
  likes       integer not null default 0,
  created_at  timestamptz not null default now()
);

-- GALLERY
create table if not exists gallery (
  id          uuid primary key default gen_random_uuid(),
  url         text not null,
  title       text,
  caption     text,
  likes       integer not null default 0,
  created_at  timestamptz not null default now()
);

-- SNIPPETS
create table if not exists snippets (
  id          uuid primary key default gen_random_uuid(),
  title       text not null,
  description text,
  language    text not null default 'js',
  code        text not null,
  views       integer not null default 0,
  likes       integer not null default 0,
  created_at  timestamptz not null default now()
);

-- MUSIC
create table if not exists music (
  id          uuid primary key default gen_random_uuid(),
  title       text not null,
  artist      text not null,
  duration    text,
  url         text,
  thumbnail   text,
  lyrics      text,
  added_at    timestamptz not null default now()
);

-- GUESTBOOK (public messages, threaded replies, admin moderation)
-- owner_token: random secret generated client-side at post time, kept only in
-- the poster's own localStorage, and required (matched server-side) to allow
-- a non-admin delete of their own message. Never exposed to other visitors.
create table if not exists guestbook (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  message      text not null,
  parent_id    uuid references guestbook(id) on delete cascade,
  is_admin     boolean not null default false,
  likes        integer not null default 0,
  owner_token  uuid not null default gen_random_uuid(),
  created_at   timestamptz not null default now()
);
create index if not exists guestbook_parent_idx on guestbook(parent_id);

-- SETTINGS (passphrase hash, dll)
create table if not exists settings (
  key         text primary key,
  value       text not null,
  updated_at  timestamptz not null default now()
);

-- Default passphrase (ganti setelah setup!)
insert into settings (key, value)
values ('admin_pass', 'mysite2025')
on conflict (key) do nothing;

-- ── Row Level Security ────────────────────────────
-- Notes, gallery, snippets, music: publik bisa baca & tulis (admin auth
-- dilakukan di app level, bukan RLS).
-- Guestbook: publik bisa baca (lewat view guestbook_public) & insert bebas,
-- tapi delete WAJIB lewat RPC delete_guestbook_entry (lihat di bawah) —
-- ini yang benar-benar mencegah satu pengunjung menghapus pesan pengunjung
-- lain, karena tidak ada policy delete langsung untuk anon di table ini.

alter table notes     enable row level security;
alter table gallery   enable row level security;
alter table snippets  enable row level security;
alter table music     enable row level security;
alter table guestbook enable row level security;
alter table settings  enable row level security;

-- PUBLIC READ untuk notes, gallery, snippets, music
create policy "public read notes"     on notes     for select using (true);
create policy "public read gallery"   on gallery   for select using (true);
create policy "public read snippets"  on snippets  for select using (true);
create policy "public read music"     on music     for select using (true);
create policy "anon read settings"    on settings  for select using (true);

-- Guestbook: NO direct public select policy — owner_token must never be
-- readable by other visitors. Public reads go through the guestbook_public
-- view below (which omits owner_token) instead of querying the table.

-- ANON WRITE untuk notes/gallery/snippets/music (admin auth handled di app level)
create policy "anon write notes"     on notes     for all using (true) with check (true);
create policy "anon write gallery"   on gallery   for all using (true) with check (true);
create policy "anon write snippets"  on snippets  for all using (true) with check (true);
create policy "anon write music"     on music     for all using (true) with check (true);
create policy "anon write settings"  on settings  for all using (true) with check (true);

-- Guestbook INSERT: anyone can post (owner_token is server-generated by default,
-- client never sets it directly)
create policy "anon insert guestbook" on guestbook for insert with check (true);
-- No direct UPDATE/DELETE/SELECT policy on guestbook for anon — all deletes go
-- through the delete_guestbook_entry() RPC below, which validates ownership or
-- admin passphrase before deleting. This is what actually stops one visitor
-- from deleting another visitor's message: even a hand-crafted API call
-- can't bypass it, because RLS blocks direct delete/select entirely.

-- Public-facing view: everything except owner_token
create or replace view guestbook_public as
  select id, name, message, parent_id, is_admin, likes, created_at
  from guestbook;

grant select on guestbook_public to anon, authenticated;

-- ── Increment functions ────────────────────────────

-- Increment likes
create or replace function increment_likes(table_name text, row_id uuid)
returns void language plpgsql as $$
begin
  execute format('update %I set likes = likes + 1 where id = $1', table_name)
  using row_id;
end;
$$;

-- Decrement likes
create or replace function decrement_likes(table_name text, row_id uuid)
returns void language plpgsql as $$
begin
  execute format('update %I set likes = greatest(likes - 1, 0) where id = $1', table_name)
  using row_id;
end;
$$;

-- Increment views (snippets)
create or replace function increment_views(row_id uuid)
returns void language plpgsql as $$
begin
  update snippets set views = views + 1 where id = row_id;
end;
$$;

-- ── Guestbook: post & delete via RPC (security definer bypasses the
-- lack of anon select/delete policy on the base table, but only through
-- these controlled entry points) ────────────────────────────

-- Post a message or reply. Returns the new row's id and owner_token —
-- the token is shown to the poster exactly once and must be saved
-- client-side (localStorage) to allow deleting it later.
create or replace function post_guestbook_entry(
  p_name text, p_message text, p_parent_id uuid default null, p_is_admin boolean default false
)
returns table(id uuid, owner_token uuid)
language plpgsql security definer as $$
declare
  new_id uuid;
  new_token uuid := gen_random_uuid();
begin
  insert into guestbook (name, message, parent_id, is_admin, owner_token)
  values (p_name, p_message, p_parent_id, p_is_admin, new_token)
  returning guestbook.id into new_id;

  return query select new_id, new_token;
end;
$$;

-- Delete a message the caller owns (token must match) OR any message when
-- the correct admin passphrase is supplied. Every other combination is
-- silently rejected — this is the actual enforcement point, not the UI.
create or replace function delete_guestbook_entry(
  p_id uuid, p_owner_token uuid default null, p_admin_pass text default null
)
returns boolean
language plpgsql security definer as $$
declare
  real_token uuid;
  real_pass  text;
begin
  select owner_token into real_token from guestbook where id = p_id;
  if real_token is null then
    return false; -- row doesn't exist
  end if;

  -- Treat an empty-string passphrase the same as "not supplied" — the
  -- client always sends a string, so this avoids accidentally taking the
  -- admin branch for a logged-out visitor.
  if p_admin_pass is not null and length(trim(p_admin_pass)) > 0 then
    select value into real_pass from settings where key = 'admin_pass';
    if real_pass is not null and real_pass = p_admin_pass then
      delete from guestbook where id = p_id;
      return true;
    end if;
    return false;
  end if;

  if p_owner_token is not null and p_owner_token = real_token then
    delete from guestbook where id = p_id;
    return true;
  end if;

  return false;
end;
$$;
